#!/usr/bin/env bun
/**
 * Compile the bus to a real single binary, dashboard included.
 *
 * The awkward part is the dashboard: `bun build --compile` can only embed
 * imports it can *see*, and the dashboard is a directory of content-hashed
 * filenames that do not exist until Vite has run. So this generates a module
 * with one static `import … with { type: "file" }` per built asset, compiles
 * against it, and puts the stub back. A dynamic import of a computed path —
 * the obvious approach — survives `bun run` and silently breaks under
 * `--compile`, which is the failure this whole dance exists to avoid.
 *
 *   bun scripts/build-binary.ts                    the host platform
 *   bun scripts/build-binary.ts --all              every supported target
 *   bun scripts/build-binary.ts --target bun-linux-x64
 */
import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

const argv = process.argv.slice(2);
const has = (name: string) => argv.includes(`--${name}`);
const flag = (name: string, fallback?: string) => {
  const index = argv.indexOf(`--${name}`);
  return index < 0 ? fallback : (argv[index + 1] ?? fallback);
};

const TARGETS = [
  "bun-linux-x64",
  "bun-linux-arm64",
  "bun-darwin-arm64",
  "bun-darwin-x64",
] as const;

const root = resolve(import.meta.dir, "..");
const generated = `${root}/src/dashboard/embedded.generated.ts`;
const dashboard = `${root}/dist/dashboard`;
const outDir = `${root}/dist/bin`;

const stub = await readFile(generated, "utf8");

async function run(command: string[], label: string) {
  const child = Bun.spawn(command, { cwd: root, stdout: "inherit", stderr: "inherit" });
  if ((await child.exited) !== 0) throw new Error(`${label} failed`);
}

/** Every file under `dist/dashboard`, as paths the server will be asked for. */
async function assets(directory: string, prefix = ""): Promise<string[]> {
  const out: string[] = [];
  for (const entry of await readdir(directory, { withFileTypes: true })) {
    if (entry.isDirectory())
      out.push(...(await assets(`${directory}/${entry.name}`, `${prefix}/${entry.name}`)));
    else out.push(`${prefix}/${entry.name}`);
  }
  return out;
}

async function writeManifest() {
  const files = await assets(dashboard);
  const imports: string[] = [];
  const entries: string[] = [];
  files.forEach((file, index) => {
    const name = `asset${index}`;
    imports.push(
      `import ${name} from "../../dist/dashboard${file}" with { type: "file" };`,
    );
    entries.push(`  ${JSON.stringify(file)}: ${name},`);
  });
  await writeFile(
    generated,
    `// Generated by scripts/build-binary.ts. Do not edit; see the stub in git.\n${imports.join(
      "\n",
    )}\n\nexport const EMBEDDED_ASSETS: Record<string, string> = {\n${entries.join(
      "\n",
    )}\n};\n`,
  );
  return files.length;
}

try {
  if (!(await Bun.file(`${dashboard}/index.html`).exists()))
    await run(["bun", "run", "build"], "bun run build");

  const embedded = await writeManifest();
  console.log(`embedding ${embedded} dashboard files`);
  await mkdir(outDir, { recursive: true });

  const targets = has("all")
    ? [...TARGETS]
    : [flag("target") ?? `bun-${process.platform === "darwin" ? "darwin" : "linux"}-${process.arch === "arm64" ? "arm64" : "x64"}`];

  for (const target of targets) {
    const outfile = `${outDir}/bql-${target.replace(/^bun-/, "")}`;
    await run(
      [
        "bun",
        "build",
        "--compile",
        `--target=${target}`,
        "../db/src/cli.ts",
        "--outfile",
        outfile,
      ],
      `compile ${target}`,
    );
    const size = Bun.file(outfile).size;
    console.log(`${outfile}  ${(size / 1024 / 1024).toFixed(1)} MiB`);
  }

  // Checksums, so a release asset can be verified without trusting the page it
  // was downloaded from.
  const lines: string[] = [];
  for (const entry of await readdir(outDir)) {
    if (entry.endsWith(".sha256") || entry === "checksums.txt") continue;
    const bytes = await Bun.file(`${outDir}/${entry}`).arrayBuffer();
    const digest = new Bun.CryptoHasher("sha256")
      .update(new Uint8Array(bytes))
      .digest("hex");
    lines.push(`${digest}  ${entry}`);
  }
  await writeFile(`${outDir}/checksums.txt`, `${lines.join("\n")}\n`);
  console.log(`\n${outDir}/checksums.txt`);
} finally {
  // Always restore the stub, including after a failure: leaving the generated
  // manifest behind would make the next `bun run` from source import files
  // that may not be there.
  await writeFile(generated, stub);
}
