// Invariant: every numeric constant here is transcribed from sqlite3.h and never computed at
// runtime, so the driver's meaning of a code cannot drift from the library it is talking to.

/** Primary and extended result codes, keyed by numeric value. */
export const RESULT_CODE_NAMES: Readonly<Record<number, string>> = {
  0: "SQLITE_OK",
  1: "SQLITE_ERROR",
  2: "SQLITE_INTERNAL",
  3: "SQLITE_PERM",
  4: "SQLITE_ABORT",
  5: "SQLITE_BUSY",
  6: "SQLITE_LOCKED",
  7: "SQLITE_NOMEM",
  8: "SQLITE_READONLY",
  9: "SQLITE_INTERRUPT",
  10: "SQLITE_IOERR",
  11: "SQLITE_CORRUPT",
  12: "SQLITE_NOTFOUND",
  13: "SQLITE_FULL",
  14: "SQLITE_CANTOPEN",
  15: "SQLITE_PROTOCOL",
  16: "SQLITE_EMPTY",
  17: "SQLITE_SCHEMA",
  18: "SQLITE_TOOBIG",
  19: "SQLITE_CONSTRAINT",
  20: "SQLITE_MISMATCH",
  21: "SQLITE_MISUSE",
  22: "SQLITE_NOLFS",
  23: "SQLITE_AUTH",
  24: "SQLITE_FORMAT",
  25: "SQLITE_RANGE",
  26: "SQLITE_NOTADB",
  27: "SQLITE_NOTICE",
  28: "SQLITE_WARNING",
  100: "SQLITE_ROW",
  101: "SQLITE_DONE",
  257: "SQLITE_ERROR_MISSING_COLLSEQ",
  513: "SQLITE_ERROR_RETRY",
  769: "SQLITE_ERROR_SNAPSHOT",
  1025: "SQLITE_ERROR_RESERVESIZE",
  1281: "SQLITE_ERROR_KEY",
  1537: "SQLITE_ERROR_UNABLE",
  266: "SQLITE_IOERR_READ",
  522: "SQLITE_IOERR_SHORT_READ",
  778: "SQLITE_IOERR_WRITE",
  1034: "SQLITE_IOERR_FSYNC",
  1290: "SQLITE_IOERR_DIR_FSYNC",
  1546: "SQLITE_IOERR_TRUNCATE",
  1802: "SQLITE_IOERR_FSTAT",
  2058: "SQLITE_IOERR_UNLOCK",
  2314: "SQLITE_IOERR_RDLOCK",
  2570: "SQLITE_IOERR_DELETE",
  2826: "SQLITE_IOERR_BLOCKED",
  3082: "SQLITE_IOERR_NOMEM",
  3338: "SQLITE_IOERR_ACCESS",
  3594: "SQLITE_IOERR_CHECKRESERVEDLOCK",
  3850: "SQLITE_IOERR_LOCK",
  4106: "SQLITE_IOERR_CLOSE",
  4362: "SQLITE_IOERR_DIR_CLOSE",
  4618: "SQLITE_IOERR_SHMOPEN",
  4874: "SQLITE_IOERR_SHMSIZE",
  5130: "SQLITE_IOERR_SHMLOCK",
  5386: "SQLITE_IOERR_SHMMAP",
  5642: "SQLITE_IOERR_SEEK",
  5898: "SQLITE_IOERR_DELETE_NOENT",
  6154: "SQLITE_IOERR_MMAP",
  6410: "SQLITE_IOERR_GETTEMPPATH",
  6666: "SQLITE_IOERR_CONVPATH",
  6922: "SQLITE_IOERR_VNODE",
  7178: "SQLITE_IOERR_AUTH",
  7434: "SQLITE_IOERR_BEGIN_ATOMIC",
  7690: "SQLITE_IOERR_COMMIT_ATOMIC",
  7946: "SQLITE_IOERR_ROLLBACK_ATOMIC",
  8202: "SQLITE_IOERR_DATA",
  8458: "SQLITE_IOERR_CORRUPTFS",
  8714: "SQLITE_IOERR_IN_PAGE",
  8970: "SQLITE_IOERR_BADKEY",
  9226: "SQLITE_IOERR_CODEC",
  262: "SQLITE_LOCKED_SHAREDCACHE",
  518: "SQLITE_LOCKED_VTAB",
  261: "SQLITE_BUSY_RECOVERY",
  517: "SQLITE_BUSY_SNAPSHOT",
  773: "SQLITE_BUSY_TIMEOUT",
  270: "SQLITE_CANTOPEN_NOTEMPDIR",
  526: "SQLITE_CANTOPEN_ISDIR",
  782: "SQLITE_CANTOPEN_FULLPATH",
  1038: "SQLITE_CANTOPEN_CONVPATH",
  1294: "SQLITE_CANTOPEN_DIRTYWAL",
  1550: "SQLITE_CANTOPEN_SYMLINK",
  267: "SQLITE_CORRUPT_VTAB",
  523: "SQLITE_CORRUPT_SEQUENCE",
  779: "SQLITE_CORRUPT_INDEX",
  264: "SQLITE_READONLY_RECOVERY",
  520: "SQLITE_READONLY_CANTLOCK",
  776: "SQLITE_READONLY_ROLLBACK",
  1032: "SQLITE_READONLY_DBMOVED",
  1288: "SQLITE_READONLY_CANTINIT",
  1544: "SQLITE_READONLY_DIRECTORY",
  516: "SQLITE_ABORT_ROLLBACK",
  275: "SQLITE_CONSTRAINT_CHECK",
  531: "SQLITE_CONSTRAINT_COMMITHOOK",
  787: "SQLITE_CONSTRAINT_FOREIGNKEY",
  1043: "SQLITE_CONSTRAINT_FUNCTION",
  1299: "SQLITE_CONSTRAINT_NOTNULL",
  1555: "SQLITE_CONSTRAINT_PRIMARYKEY",
  1811: "SQLITE_CONSTRAINT_TRIGGER",
  2067: "SQLITE_CONSTRAINT_UNIQUE",
  2323: "SQLITE_CONSTRAINT_VTAB",
  2579: "SQLITE_CONSTRAINT_ROWID",
  2835: "SQLITE_CONSTRAINT_PINNED",
  3091: "SQLITE_CONSTRAINT_DATATYPE",
  283: "SQLITE_NOTICE_RECOVER_WAL",
  539: "SQLITE_NOTICE_RECOVER_ROLLBACK",
  795: "SQLITE_NOTICE_RBU",
  284: "SQLITE_WARNING_AUTOINDEX",
  279: "SQLITE_AUTH_USER",
  256: "SQLITE_OK_LOAD_PERMANENTLY",
  512: "SQLITE_OK_SYMLINK",
}

export const SQLITE_OK = 0
export const SQLITE_ERROR = 1
export const SQLITE_BUSY = 5
export const SQLITE_LOCKED = 6
export const SQLITE_NOMEM = 7
export const SQLITE_INTERRUPT = 9
export const SQLITE_MISUSE = 21
export const SQLITE_ROW = 100
export const SQLITE_DONE = 101

/** `sqlite3_open_v2` flags. */
export const SQLITE_OPEN_READONLY = 0x00000001
export const SQLITE_OPEN_READWRITE = 0x00000002
export const SQLITE_OPEN_CREATE = 0x00000004
export const SQLITE_OPEN_URI = 0x00000040
export const SQLITE_OPEN_MEMORY = 0x00000080
export const SQLITE_OPEN_NOMUTEX = 0x00008000
export const SQLITE_OPEN_FULLMUTEX = 0x00010000

/** `sqlite3_prepare_v3` flags. */
export const SQLITE_PREPARE_PERSISTENT = 0x01
export const SQLITE_PREPARE_NO_VTAB = 0x04

/** Column storage classes returned by `sqlite3_column_type`. */
export const SQLITE_INTEGER = 1
export const SQLITE_FLOAT = 2
export const SQLITE_TEXT = 3
export const SQLITE_BLOB = 4
export const SQLITE_NULL = 5

/** Authorizer callback return values. */
export const SQLITE_DENY = 1
export const SQLITE_IGNORE = 2

/** Authorizer action codes (2nd argument to the authorizer callback). */
export const SQLITE_CREATE_INDEX = 1
export const SQLITE_CREATE_TABLE = 2
export const SQLITE_CREATE_TEMP_INDEX = 3
export const SQLITE_CREATE_TEMP_TABLE = 4
export const SQLITE_CREATE_TEMP_TRIGGER = 5
export const SQLITE_CREATE_TEMP_VIEW = 6
export const SQLITE_CREATE_TRIGGER = 7
export const SQLITE_CREATE_VIEW = 8
export const SQLITE_DELETE = 9
export const SQLITE_DROP_INDEX = 10
export const SQLITE_DROP_TABLE = 11
export const SQLITE_DROP_TEMP_INDEX = 12
export const SQLITE_DROP_TEMP_TABLE = 13
export const SQLITE_DROP_TEMP_TRIGGER = 14
export const SQLITE_DROP_TEMP_VIEW = 15
export const SQLITE_DROP_TRIGGER = 16
export const SQLITE_DROP_VIEW = 17
export const SQLITE_INSERT = 18
export const SQLITE_PRAGMA = 19
export const SQLITE_READ = 20
export const SQLITE_SELECT = 21
export const SQLITE_TRANSACTION = 22
export const SQLITE_UPDATE = 23
export const SQLITE_ATTACH = 24
export const SQLITE_DETACH = 25
export const SQLITE_ALTER_TABLE = 26
export const SQLITE_REINDEX = 27
export const SQLITE_ANALYZE = 28
export const SQLITE_CREATE_VTABLE = 29
export const SQLITE_DROP_VTABLE = 30
export const SQLITE_FUNCTION = 31
export const SQLITE_SAVEPOINT = 32
export const SQLITE_COPY = 0
export const SQLITE_RECURSIVE = 33

/** Human-readable names for authorizer action codes, for logging and ACL rules. */
export const AUTHORIZER_ACTION_NAMES: Readonly<Record<number, string>> = {
  0: "SQLITE_COPY",
  1: "SQLITE_CREATE_INDEX",
  2: "SQLITE_CREATE_TABLE",
  3: "SQLITE_CREATE_TEMP_INDEX",
  4: "SQLITE_CREATE_TEMP_TABLE",
  5: "SQLITE_CREATE_TEMP_TRIGGER",
  6: "SQLITE_CREATE_TEMP_VIEW",
  7: "SQLITE_CREATE_TRIGGER",
  8: "SQLITE_CREATE_VIEW",
  9: "SQLITE_DELETE",
  10: "SQLITE_DROP_INDEX",
  11: "SQLITE_DROP_TABLE",
  12: "SQLITE_DROP_TEMP_INDEX",
  13: "SQLITE_DROP_TEMP_TABLE",
  14: "SQLITE_DROP_TEMP_TRIGGER",
  15: "SQLITE_DROP_TEMP_VIEW",
  16: "SQLITE_DROP_TRIGGER",
  17: "SQLITE_DROP_VIEW",
  18: "SQLITE_INSERT",
  19: "SQLITE_PRAGMA",
  20: "SQLITE_READ",
  21: "SQLITE_SELECT",
  22: "SQLITE_TRANSACTION",
  23: "SQLITE_UPDATE",
  24: "SQLITE_ATTACH",
  25: "SQLITE_DETACH",
  26: "SQLITE_ALTER_TABLE",
  27: "SQLITE_REINDEX",
  28: "SQLITE_ANALYZE",
  29: "SQLITE_CREATE_VTABLE",
  30: "SQLITE_DROP_VTABLE",
  31: "SQLITE_FUNCTION",
  32: "SQLITE_SAVEPOINT",
  33: "SQLITE_RECURSIVE",
}

/** `sqlite3_limit` categories. */
export const LIMITS = {
  SQLITE_LIMIT_LENGTH: 0,
  SQLITE_LIMIT_SQL_LENGTH: 1,
  SQLITE_LIMIT_COLUMN: 2,
  SQLITE_LIMIT_EXPR_DEPTH: 3,
  SQLITE_LIMIT_COMPOUND_SELECT: 4,
  SQLITE_LIMIT_VDBE_OP: 5,
  SQLITE_LIMIT_FUNCTION_ARG: 6,
  SQLITE_LIMIT_ATTACHED: 7,
  SQLITE_LIMIT_LIKE_PATTERN_LENGTH: 8,
  SQLITE_LIMIT_VARIABLE_NUMBER: 9,
  SQLITE_LIMIT_TRIGGER_DEPTH: 10,
  SQLITE_LIMIT_WORKER_THREADS: 11,
  SQLITE_LIMIT_PARSER_DEPTH: 12,
} as const

export type LimitName = keyof typeof LIMITS

export const SQLITE_LIMIT_LENGTH = 0
export const SQLITE_LIMIT_SQL_LENGTH = 1
export const SQLITE_LIMIT_COLUMN = 2
export const SQLITE_LIMIT_EXPR_DEPTH = 3
export const SQLITE_LIMIT_COMPOUND_SELECT = 4
export const SQLITE_LIMIT_VDBE_OP = 5
export const SQLITE_LIMIT_FUNCTION_ARG = 6
export const SQLITE_LIMIT_ATTACHED = 7
export const SQLITE_LIMIT_LIKE_PATTERN_LENGTH = 8
export const SQLITE_LIMIT_VARIABLE_NUMBER = 9
export const SQLITE_LIMIT_TRIGGER_DEPTH = 10
export const SQLITE_LIMIT_WORKER_THREADS = 11
export const SQLITE_LIMIT_PARSER_DEPTH = 12

/** `sqlite3_file_control` opcodes we expose by name. */
export const FILE_CONTROLS = {
  SQLITE_FCNTL_LOCKSTATE: 1,
  SQLITE_FCNTL_SIZE_HINT: 5,
  SQLITE_FCNTL_CHUNK_SIZE: 6,
  SQLITE_FCNTL_PERSIST_WAL: 10,
  SQLITE_FCNTL_POWERSAFE_OVERWRITE: 13,
  SQLITE_FCNTL_MMAP_SIZE: 18,
  SQLITE_FCNTL_HAS_MOVED: 20,
  SQLITE_FCNTL_COMMIT_PHASETWO: 22,
  SQLITE_FCNTL_WAL_BLOCK: 24,
  SQLITE_FCNTL_LOCK_TIMEOUT: 34,
  SQLITE_FCNTL_DATA_VERSION: 35,
  SQLITE_FCNTL_SIZE_LIMIT: 36,
  SQLITE_FCNTL_CKPT_DONE: 37,
  SQLITE_FCNTL_RESERVE_BYTES: 38,
  SQLITE_FCNTL_CKPT_START: 39,
  SQLITE_FCNTL_EXTERNAL_READER: 40,
  SQLITE_FCNTL_RESET_CACHE: 42,
} as const

export type FileControlName = keyof typeof FILE_CONTROLS

/** `sqlite3_wal_checkpoint_v2` modes. */
export const CHECKPOINT_MODES = {
  PASSIVE: 0,
  FULL: 1,
  RESTART: 2,
  TRUNCATE: 3,
} as const

export type CheckpointMode = keyof typeof CHECKPOINT_MODES

/** `sqlite3_update_hook` / preupdate operation codes. */
export const UPDATE_OPS: Readonly<Record<number, "insert" | "update" | "delete">> = {
  18: "insert",
  23: "update",
  9: "delete",
}
