// The public surface of replication: the wire codec both halves share, the primary's endpoint and
// the replica's client. Design §8, `docs/plan-phase1.md`, as-built notes in `docs/r1-replication.md`.

export {
  ACK_FSYNCED,
  type AckBody,
  decodeAck,
  decodeJson,
  decodeSnapshotChunk,
  decodeTxn,
  encodeAck,
  encodeFrame,
  encodeJson,
  encodeSnapshotChunk,
  encodeTxn,
  type ErrorBody,
  FATAL_CODES,
  type ForwardBody,
  FRAME,
  FRAME_HEADER_SIZE,
  type Frame,
  FrameReader,
  type FrameType,
  frameName,
  type HeartbeatBody,
  type HelloBody,
  makeNonce,
  makeProof,
  MAX_BODY_BYTES,
  ProtocolError,
  PROTO_VERSION,
  type ReplicationErrorCode,
  type ResultBody,
  type SnapshotBeginBody,
  type SnapshotChunkBody,
  type SnapshotEndBody,
  type SubscribeBody,
  type SubscribedBody,
  type TxnBody,
  type UnsubscribeBody,
  verifyProof,
} from "./protocol.ts"
export {
  AckTimeout,
  AckTracker,
  type AckTrackerOptions,
  type AckOutcome,
  NoReplicas,
} from "./ack.ts"
export {
  type AckEvent,
  type ReplicaView,
  ReplicationServer,
  type ReplicationServerOptions,
  type ReplicationSocket,
} from "./primary.ts"
export {
  type ClientSocket,
  ForwardError,
  type ForwardRequest,
  ReplicaClient,
  type ReplicaClientOptions,
  ReplicaOffline,
  type ReplicaStatus,
  type SocketFactory,
  type StreamStatus,
} from "./replica.ts"
